In [2]:
#!pip install torch

In [3]:
import torch

/Users/anmolgautam/Documents/learning/pytorch-learning-from-scratch/.venv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [4]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [5]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
x.shape

torch.Size([2, 3])

In [7]:
x.ndim

2

In [8]:
x.shape[1]

3

In [9]:
x[0]

tensor([1, 2, 3])

In [10]:
x[0].shape

torch.Size([3])

In [11]:
x[0][1]

tensor(2)

In [12]:
x[0][1].shape

torch.Size([])

In [13]:
x[0,1]

tensor(2)

In [14]:
x[:,1]

tensor([2, 5])

In [15]:
x[:,1].shape

torch.Size([2])

In [16]:
x[:,1:2]

tensor([[2],
        [5]])

In [17]:
x[:, 1:2].shape


torch.Size([2, 1])

In [18]:
x.dtype

torch.int64

In [19]:
y = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
y.dtype

torch.float32

In [20]:
x + 0.5

tensor([[1.5000, 2.5000, 3.5000],
        [4.5000, 5.5000, 6.5000]])

In [21]:
(x + 0.5).dtype

torch.float32

In [22]:
x.device

device(type='cpu')

In [23]:
torch.backends.mps.is_available()

True

In [24]:
z = torch.tensor([1.0, 2.0, 3.0], device="mps")

In [25]:
z.device

device(type='mps', index=0)

In [26]:
x.device

device(type='cpu')

In [27]:
z.device

device(type='mps', index=0)

In [28]:
x+z

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [29]:
x_mps = x.to("mps")

In [30]:
x_mps.device

device(type='mps', index=0)

In [31]:
x_mps.shape

torch.Size([2, 3])

In [32]:
z.shape

torch.Size([3])

In [33]:
x_mps + z

tensor([[2., 4., 6.],
        [5., 7., 9.]], device='mps:0')

In [35]:
(x_mps + z).shape

torch.Size([2, 3])

In [36]:
a = torch.tensor([10.0, 20.0], device="mps")
x_mps + a

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [37]:
a_col = a.reshape(2, 1)
a_col.shape

torch.Size([2, 1])

In [38]:
x_mps + a_col


tensor([[11., 12., 13.],
        [24., 25., 26.]], device='mps:0')

In [39]:
b = torch.tensor([[1], [2], [3]])
b.shape

torch.Size([3, 1])

In [40]:
c = torch.tensor([1, 2, 3])
c.shape

torch.Size([3])

In [41]:
e = torch.tensor([
    [[1, 2, 3]],
    [[4, 5, 6]]
])
e.shape

torch.Size([2, 1, 3])

In [43]:
a = torch.tensor([7, 8, 9, 10])
a.shape

torch.Size([4])

In [44]:
b = torch.tensor([[7, 8, 9, 10]])
b.shape

torch.Size([1, 4])

In [45]:
c = torch.tensor([[7], [8], [9], [10]])
c.shape

torch.Size([4, 1])

In [46]:
d = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
d.ndim

2

In [47]:
d.shape[0]

2

In [48]:
d.shape[1]

3

In [50]:
d[0].shape

torch.Size([3])

In [51]:
d[:,1]

tensor([2, 5])

In [53]:
d[:,1:2].shape

torch.Size([2, 1])

In [54]:
d[1,2]

tensor(6)