# Lesson 02: Reshape

Goal: learn how tensor shape can be changed without changing the underlying values.

In [1]:
import torch

/Users/anmolgautam/Documents/learning/pytorch-learning-from-scratch/.venv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x.shape

torch.Size([6])

In [3]:
x.reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
x.reshape(2,3).shape

torch.Size([2, 3])

In [5]:
x.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
x.reshape(2,2)

RuntimeError: shape '[2, 2]' is invalid for input of size 6

In [8]:
x.numel()

6

In [9]:
y = x.reshape(2,3)
y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
y.reshape(6)

tensor([1, 2, 3, 4, 5, 6])

In [12]:
y.reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [13]:
y.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [14]:
x.reshape(2,-1)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.reshape(-1,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [16]:
x.reshape(-1,-1)

RuntimeError: only one dimension can be inferred

In [17]:
z = torch.tensor([[1, 2, 3], [4, 5, 6]])
z.shape

torch.Size([2, 3])

In [18]:
z.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
z.reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])