# Lesson 03: Squeeze and Unsqueeze

In [1]:
import torch

/Users/anmolgautam/Documents/learning/pytorch-learning-from-scratch/.venv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
x = torch.tensor([[1], [2], [3]])
x.shape

torch.Size([3, 1])

In [3]:
x.squeeze()

tensor([1, 2, 3])

In [4]:
y = torch.tensor([[[5]]])
y.shape

torch.Size([1, 1, 1])

In [5]:
y.squeeze()

tensor(5)

In [6]:
y.squeeze().shape

torch.Size([])

In [7]:
z = torch.tensor([1, 2, 3])
z.shape

torch.Size([3])

In [8]:
z.unsqueeze(0)

tensor([[1, 2, 3]])

In [9]:
z.unsqueeze(0).shape

torch.Size([1, 3])

In [11]:
z.unsqueeze(1).shape

torch.Size([3, 1])

In [12]:
a = torch.tensor([[1, 2, 3]])
a.shape

torch.Size([1, 3])

In [13]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
b.shape

torch.Size([2, 3])

In [14]:
b.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
c = torch.tensor([[[1], [2], [3]]])
c.shape

torch.Size([1, 3, 1])

In [16]:
c.squeeze()

tensor([1, 2, 3])

In [17]:
c.squeeze(0).shape

torch.Size([3, 1])

In [18]:
b.squeeze(0)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
z = torch.tensor([1, 2, 3])
print(z.shape)
z.unsqueeze(-1).shape

torch.Size([3])


torch.Size([3, 1])

In [23]:
z.unsqueeze(-1)

tensor([[1],
        [2],
        [3]])

In [24]:
a = torch.tensor([[1, 2, 3]])
a.shape

torch.Size([1, 3])

In [27]:
a.unsqueeze(-1)

tensor([[[1],
         [2],
         [3]]])