# Lesson 04: Flatten

In [2]:
import torch

/Users/anmolgautam/Documents/learning/pytorch-learning-from-scratch/.venv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape [2, 3]
x.shape

torch.Size([2, 3])

In [4]:
x.flatten()

tensor([1, 2, 3, 4, 5, 6])

In [5]:
x.flatten().shape

torch.Size([6])

In [6]:
y = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])  # shape [2, 2, 2]

y.shape

torch.Size([2, 2, 2])

In [7]:
y.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
y.flatten(start_dim=1)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [9]:
y.flatten(start_dim=1).shape

torch.Size([2, 4])

In [10]:
z = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
z.shape

torch.Size([2, 2, 3])

In [12]:
z.flatten(start_dim=1).shape

torch.Size([2, 6])

In [14]:
z.flatten(start_dim=0,end_dim=1).shape

torch.Size([4, 3])

Shape comments matter from here on. When useful, write the expected shape beside a tensor before running the cell.

## Exercises

Solve these on your own at the end of the lesson.